channel_sources:
- adrianinsaval,conda-forge
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - '10.13'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
c_compiler_version:        # [osx]
  # clang 16 errors on incompatible function pointers
  - 15                     # [osx]
cxx_compiler_version:      # [osx]
  - 15                     # [osx]
