MACOSX_SDK_VERSION:        # [osx]
  - '10.14'                # [osx and x86_64]
  - '13.3'                # [osx and arm64]
c_compiler_version:        # [osx]
  - 17                     # [osx]
cxx_compiler_version:      # [osx]
  - 17                     # [osx]
c_compiler:                # [win]
  - vs2022                 # [win]
cxx_compiler:              # [win]
  - vs2022                 # [win]
c_stdlib_version:          # [linux]
  - "2.17"                 # [linux]
